New documentation S.Port Firmware Flashing
opentx/opentx-taranis-manual pull request #15
Opened 2017-04-29 15:44 UTC by RCdiy

2017-04-29 16:06 UTC, schwabe requested changes

2017-04-29 16:06 UTC, schwabe commented on s-port_flashing.md
> +  ![](images/sport-flash-104-sd-hc-firmware.bmp)
Convert the bmp to png if possible.

2017-04-29 16:06 UTC, schwabe commented on s-port_flashing.md
> +  Check that the device being flashed is rated for the transmitter’s battery voltage
Add a paragraph: This is true for X9D+ standard batteries (6 cell Nimah) and most Sport devices . For X12S and X9E this is not true but only slightly outside the range and reportely works. But try at your own risk.

2017-04-29 16:06 UTC, schwabe commented on s-port_flashing.md
> +
Remove these two lines and add a something like

Note: Adding manually the Sport pins to a X7 variant shipped without the sport pins will not work as this requires also a newer PCB revision.

to the non sport section.

2017-04-29 17:14 UTC, RCdiy commented on s-port_flashing.md
> +  ![](images/sport-flash-104-sd-hc-firmware.bmp)
How do I do this? Update the file in my fork and do a new pull request? Not sure how this works...

2017-04-29 17:16 UTC, RCdiy commented on s-port_flashing.md
> +
Same as saying will not work :)

2017-04-29 17:17 UTC, RCdiy commented on s-port_flashing.md
> +  ![](images/sport-flash-104-sd-hc-firmware.bmp)
If bmp works lets leave it... I'll change them later or someone else can:)

2017-04-29 17:20 UTC, RCdiy commented on s-port_flashing.md
> +  Check that the device being flashed is rated for the transmitter’s battery voltage
Making it more verbose unnecessarily... I'm focusing on the flashing...
But... the extra wording can be added by anyone once posted:)

2017-04-29 17:24 UTC, RCdiy commented
Future documentation will be posted in an issue. It can be edited there and once consensus reached the file will be updated and a pull request made.
My thoughts are to accept this pull request and either an admin makes the changes or waits till I do:)
Mike Barsalou and I are working on a draft for a workflow wiki so we are all on the same page:)

2017-05-01 13:50 UTC, RCdiy commented
BMP changed to PNG.
Please merge.

2017-05-15 18:37 UTC, closed without merging